/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FieldRouteRouteImport } from './routes/field/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as PerformanceIndexRouteImport } from './routes/performance/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as FieldIndexRouteImport } from './routes/field/index'
import { Route as FarmsIndexRouteImport } from './routes/farms/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OpportunitiesCycleIdRouteImport } from './routes/opportunities/$cycleId'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRiskRouteImport } from './routes/legal/risk'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalInvestmentAgreementRouteImport } from './routes/legal/investment-agreement'
import { Route as FarmsFarmSlugRouteImport } from './routes/farms/$farmSlug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthKycRouteImport } from './routes/auth/kyc'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppWalletRouteImport } from './routes/app/wallet'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as FieldProfileIndexRouteImport } from './routes/field/profile/index'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppPerformanceIndexRouteImport } from './routes/app/performance/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app/notifications/index'
import { Route as AppInvestmentsIndexRouteImport } from './routes/app/investments/index'
import { Route as AppActivityIndexRouteImport } from './routes/app/activity/index'
import { Route as AdminWithdrawalsIndexRouteImport } from './routes/admin/withdrawals/index'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminStaffIndexRouteImport } from './routes/admin/staff/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminPerformanceIndexRouteImport } from './routes/admin/performance/index'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminInvestorsIndexRouteImport } from './routes/admin/investors/index'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin/inquiries/index'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin/gallery/index'
import { Route as AdminFarmsIndexRouteImport } from './routes/admin/farms/index'
import { Route as AdminFaqIndexRouteImport } from './routes/admin/faq/index'
import { Route as AdminCyclesIndexRouteImport } from './routes/admin/cycles/index'
import { Route as AdminAuditIndexRouteImport } from './routes/admin/audit/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as FieldReportsNewRouteImport } from './routes/field/reports/new'
import { Route as FieldReportsReportIdRouteImport } from './routes/field/reports/$reportId'
import { Route as AppInvestCycleIdRouteImport } from './routes/app/invest/$cycleId'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as AdminTeamNewRouteImport } from './routes/admin/team/new'
import { Route as AdminTeamMemberIdRouteImport } from './routes/admin/team/$memberId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsProductSlugRouteImport } from './routes/admin/products/$productSlug'
import { Route as AdminNewsNewRouteImport } from './routes/admin/news/new'
import { Route as AdminNewsPostSlugRouteImport } from './routes/admin/news/$postSlug'
import { Route as AdminInvestorsInvestorIdRouteImport } from './routes/admin/investors/$investorId'
import { Route as AdminInquiriesInquiryIdRouteImport } from './routes/admin/inquiries/$inquiryId'
import { Route as AdminGalleryNewRouteImport } from './routes/admin/gallery/new'
import { Route as AdminGalleryItemSlugRouteImport } from './routes/admin/gallery/$itemSlug'
import { Route as AdminFarmsNewRouteImport } from './routes/admin/farms/new'
import { Route as AdminFarmsFarmSlugRouteImport } from './routes/admin/farms/$farmSlug'
import { Route as AdminFaqNewRouteImport } from './routes/admin/faq/new'
import { Route as AdminFaqFaqIdRouteImport } from './routes/admin/faq/$faqId'
import { Route as AdminCyclesNewRouteImport } from './routes/admin/cycles/new'
import { Route as AdminCyclesCycleSlugRouteImport } from './routes/admin/cycles/$cycleSlug'
import { Route as FieldReportsReportIdViewRouteImport } from './routes/field/reports/$reportId/view'
import { Route as AppReportsTransactionIdReceiptRouteImport } from './routes/app/reports/$transactionId/receipt'
import { Route as AppInvestmentsInvestmentIdCertificateRouteImport } from './routes/app/investments/$investmentId/certificate'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRouteRoute = FieldRouteRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceIndexRoute = PerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldIndexRoute = FieldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FieldRouteRoute,
} as any)
const FarmsIndexRoute = FarmsIndexRouteImport.update({
  id: '/farms/',
  path: '/farms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OpportunitiesCycleIdRoute = OpportunitiesCycleIdRouteImport.update({
  id: '/opportunities/$cycleId',
  path: '/opportunities/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRiskRoute = LegalRiskRouteImport.update({
  id: '/legal/risk',
  path: '/legal/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalInvestmentAgreementRoute =
  LegalInvestmentAgreementRouteImport.update({
    id: '/legal/investment-agreement',
    path: '/legal/investment-agreement',
    getParentRoute: () => rootRouteImport,
  } as any)
const FarmsFarmSlugRoute = FarmsFarmSlugRouteImport.update({
  id: '/farms/$farmSlug',
  path: '/farms/$farmSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthKycRoute = AuthKycRouteImport.update({
  id: '/auth/kyc',
  path: '/auth/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldProfileIndexRoute = FieldProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => FieldRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerformanceIndexRoute = AppPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvestmentsIndexRoute = AppInvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminWithdrawalsIndexRoute = AdminWithdrawalsIndexRouteImport.update({
  id: '/withdrawals/',
  path: '/withdrawals/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPerformanceIndexRoute = AdminPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvestorsIndexRoute = AdminInvestorsIndexRouteImport.update({
  id: '/investors/',
  path: '/investors/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFarmsIndexRoute = AdminFarmsIndexRouteImport.update({
  id: '/farms/',
  path: '/farms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaqIndexRoute = AdminFaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCyclesIndexRoute = AdminCyclesIndexRouteImport.update({
  id: '/cycles/',
  path: '/cycles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FieldReportsNewRoute = FieldReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => FieldRouteRoute,
} as any)
const FieldReportsReportIdRoute = FieldReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => FieldRouteRoute,
} as any)
const AppInvestCycleIdRoute = AppInvestCycleIdRouteImport.update({
  id: '/invest/$cycleId',
  path: '/invest/$cycleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamNewRoute = AdminTeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamMemberIdRoute = AdminTeamMemberIdRouteImport.update({
  id: '/team/$memberId',
  path: '/team/$memberId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsProductSlugRoute =
  AdminProductsProductSlugRouteImport.update({
    id: '/products/$productSlug',
    path: '/products/$productSlug',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsPostSlugRoute = AdminNewsPostSlugRouteImport.update({
  id: '/news/$postSlug',
  path: '/news/$postSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvestorsInvestorIdRoute =
  AdminInvestorsInvestorIdRouteImport.update({
    id: '/investors/$investorId',
    path: '/investors/$investorId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminInquiriesInquiryIdRoute = AdminInquiriesInquiryIdRouteImport.update({
  id: '/inquiries/$inquiryId',
  path: '/inquiries/$inquiryId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryNewRoute = AdminGalleryNewRouteImport.update({
  id: '/gallery/new',
  path: '/gallery/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryItemSlugRoute = AdminGalleryItemSlugRouteImport.update({
  id: '/gallery/$itemSlug',
  path: '/gallery/$itemSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFarmsNewRoute = AdminFarmsNewRouteImport.update({
  id: '/farms/new',
  path: '/farms/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFarmsFarmSlugRoute = AdminFarmsFarmSlugRouteImport.update({
  id: '/farms/$farmSlug',
  path: '/farms/$farmSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaqNewRoute = AdminFaqNewRouteImport.update({
  id: '/faq/new',
  path: '/faq/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaqFaqIdRoute = AdminFaqFaqIdRouteImport.update({
  id: '/faq/$faqId',
  path: '/faq/$faqId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCyclesNewRoute = AdminCyclesNewRouteImport.update({
  id: '/cycles/new',
  path: '/cycles/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCyclesCycleSlugRoute = AdminCyclesCycleSlugRouteImport.update({
  id: '/cycles/$cycleSlug',
  path: '/cycles/$cycleSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FieldReportsReportIdViewRoute =
  FieldReportsReportIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => FieldReportsReportIdRoute,
  } as any)
const AppReportsTransactionIdReceiptRoute =
  AppReportsTransactionIdReceiptRouteImport.update({
    id: '/reports/$transactionId/receipt',
    path: '/reports/$transactionId/receipt',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInvestmentsInvestmentIdCertificateRoute =
  AppInvestmentsInvestmentIdCertificateRouteImport.update({
    id: '/investments/$investmentId/certificate',
    path: '/investments/$investmentId/certificate',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/field': typeof FieldRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/api/health': typeof ApiHealthRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/kyc': typeof AuthKycRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/farms/$farmSlug': typeof FarmsFarmSlugRoute
  '/legal/investment-agreement': typeof LegalInvestmentAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/opportunities/$cycleId': typeof OpportunitiesCycleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/farms/': typeof FarmsIndexRoute
  '/field/': typeof FieldIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/cycles/$cycleSlug': typeof AdminCyclesCycleSlugRoute
  '/admin/cycles/new': typeof AdminCyclesNewRoute
  '/admin/faq/$faqId': typeof AdminFaqFaqIdRoute
  '/admin/faq/new': typeof AdminFaqNewRoute
  '/admin/farms/$farmSlug': typeof AdminFarmsFarmSlugRoute
  '/admin/farms/new': typeof AdminFarmsNewRoute
  '/admin/gallery/$itemSlug': typeof AdminGalleryItemSlugRoute
  '/admin/gallery/new': typeof AdminGalleryNewRoute
  '/admin/inquiries/$inquiryId': typeof AdminInquiriesInquiryIdRoute
  '/admin/investors/$investorId': typeof AdminInvestorsInvestorIdRoute
  '/admin/news/$postSlug': typeof AdminNewsPostSlugRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/products/$productSlug': typeof AdminProductsProductSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/team/$memberId': typeof AdminTeamMemberIdRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/app/invest/$cycleId': typeof AppInvestCycleIdRoute
  '/field/reports/$reportId': typeof FieldReportsReportIdRouteWithChildren
  '/field/reports/new': typeof FieldReportsNewRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/cycles/': typeof AdminCyclesIndexRoute
  '/admin/faq/': typeof AdminFaqIndexRoute
  '/admin/farms/': typeof AdminFarmsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/investors/': typeof AdminInvestorsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/performance/': typeof AdminPerformanceIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
  '/app/activity/': typeof AppActivityIndexRoute
  '/app/investments/': typeof AppInvestmentsIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/performance/': typeof AppPerformanceIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/field/profile/': typeof FieldProfileIndexRoute
  '/app/investments/$investmentId/certificate': typeof AppInvestmentsInvestmentIdCertificateRoute
  '/app/reports/$transactionId/receipt': typeof AppReportsTransactionIdReceiptRoute
  '/field/reports/$reportId/view': typeof FieldReportsReportIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/api/health': typeof ApiHealthRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/kyc': typeof AuthKycRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/farms/$farmSlug': typeof FarmsFarmSlugRoute
  '/legal/investment-agreement': typeof LegalInvestmentAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/opportunities/$cycleId': typeof OpportunitiesCycleIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/farms': typeof FarmsIndexRoute
  '/field': typeof FieldIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/news': typeof NewsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/performance': typeof PerformanceIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/cycles/$cycleSlug': typeof AdminCyclesCycleSlugRoute
  '/admin/cycles/new': typeof AdminCyclesNewRoute
  '/admin/faq/$faqId': typeof AdminFaqFaqIdRoute
  '/admin/faq/new': typeof AdminFaqNewRoute
  '/admin/farms/$farmSlug': typeof AdminFarmsFarmSlugRoute
  '/admin/farms/new': typeof AdminFarmsNewRoute
  '/admin/gallery/$itemSlug': typeof AdminGalleryItemSlugRoute
  '/admin/gallery/new': typeof AdminGalleryNewRoute
  '/admin/inquiries/$inquiryId': typeof AdminInquiriesInquiryIdRoute
  '/admin/investors/$investorId': typeof AdminInvestorsInvestorIdRoute
  '/admin/news/$postSlug': typeof AdminNewsPostSlugRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/products/$productSlug': typeof AdminProductsProductSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/team/$memberId': typeof AdminTeamMemberIdRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/app/invest/$cycleId': typeof AppInvestCycleIdRoute
  '/field/reports/$reportId': typeof FieldReportsReportIdRouteWithChildren
  '/field/reports/new': typeof FieldReportsNewRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/cycles': typeof AdminCyclesIndexRoute
  '/admin/faq': typeof AdminFaqIndexRoute
  '/admin/farms': typeof AdminFarmsIndexRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/investors': typeof AdminInvestorsIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/performance': typeof AdminPerformanceIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/admin/withdrawals': typeof AdminWithdrawalsIndexRoute
  '/app/activity': typeof AppActivityIndexRoute
  '/app/investments': typeof AppInvestmentsIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/performance': typeof AppPerformanceIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/field/profile': typeof FieldProfileIndexRoute
  '/app/investments/$investmentId/certificate': typeof AppInvestmentsInvestmentIdCertificateRoute
  '/app/reports/$transactionId/receipt': typeof AppReportsTransactionIdReceiptRoute
  '/field/reports/$reportId/view': typeof FieldReportsReportIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/field': typeof FieldRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/api/health': typeof ApiHealthRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/kyc': typeof AuthKycRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/farms/$farmSlug': typeof FarmsFarmSlugRoute
  '/legal/investment-agreement': typeof LegalInvestmentAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/opportunities/$cycleId': typeof OpportunitiesCycleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/farms/': typeof FarmsIndexRoute
  '/field/': typeof FieldIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/cycles/$cycleSlug': typeof AdminCyclesCycleSlugRoute
  '/admin/cycles/new': typeof AdminCyclesNewRoute
  '/admin/faq/$faqId': typeof AdminFaqFaqIdRoute
  '/admin/faq/new': typeof AdminFaqNewRoute
  '/admin/farms/$farmSlug': typeof AdminFarmsFarmSlugRoute
  '/admin/farms/new': typeof AdminFarmsNewRoute
  '/admin/gallery/$itemSlug': typeof AdminGalleryItemSlugRoute
  '/admin/gallery/new': typeof AdminGalleryNewRoute
  '/admin/inquiries/$inquiryId': typeof AdminInquiriesInquiryIdRoute
  '/admin/investors/$investorId': typeof AdminInvestorsInvestorIdRoute
  '/admin/news/$postSlug': typeof AdminNewsPostSlugRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/products/$productSlug': typeof AdminProductsProductSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/team/$memberId': typeof AdminTeamMemberIdRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/app/invest/$cycleId': typeof AppInvestCycleIdRoute
  '/field/reports/$reportId': typeof FieldReportsReportIdRouteWithChildren
  '/field/reports/new': typeof FieldReportsNewRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/cycles/': typeof AdminCyclesIndexRoute
  '/admin/faq/': typeof AdminFaqIndexRoute
  '/admin/farms/': typeof AdminFarmsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/investors/': typeof AdminInvestorsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/performance/': typeof AdminPerformanceIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
  '/app/activity/': typeof AppActivityIndexRoute
  '/app/investments/': typeof AppInvestmentsIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/performance/': typeof AppPerformanceIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/field/profile/': typeof FieldProfileIndexRoute
  '/app/investments/$investmentId/certificate': typeof AppInvestmentsInvestmentIdCertificateRoute
  '/app/reports/$transactionId/receipt': typeof AppReportsTransactionIdReceiptRoute
  '/field/reports/$reportId/view': typeof FieldReportsReportIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/field'
    | '/about'
    | '/contact'
    | '/api/health'
    | '/app/wallet'
    | '/auth/forgot-password'
    | '/auth/kyc'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/farms/$farmSlug'
    | '/legal/investment-agreement'
    | '/legal/privacy'
    | '/legal/risk'
    | '/legal/terms'
    | '/news/$slug'
    | '/opportunities/$cycleId'
    | '/admin/'
    | '/app/'
    | '/farms/'
    | '/field/'
    | '/gallery/'
    | '/news/'
    | '/opportunities/'
    | '/performance/'
    | '/products/'
    | '/admin/cycles/$cycleSlug'
    | '/admin/cycles/new'
    | '/admin/faq/$faqId'
    | '/admin/faq/new'
    | '/admin/farms/$farmSlug'
    | '/admin/farms/new'
    | '/admin/gallery/$itemSlug'
    | '/admin/gallery/new'
    | '/admin/inquiries/$inquiryId'
    | '/admin/investors/$investorId'
    | '/admin/news/$postSlug'
    | '/admin/news/new'
    | '/admin/products/$productSlug'
    | '/admin/products/new'
    | '/admin/team/$memberId'
    | '/admin/team/new'
    | '/api/webhooks/paystack'
    | '/app/invest/$cycleId'
    | '/field/reports/$reportId'
    | '/field/reports/new'
    | '/admin/analytics/'
    | '/admin/audit/'
    | '/admin/cycles/'
    | '/admin/faq/'
    | '/admin/farms/'
    | '/admin/gallery/'
    | '/admin/inquiries/'
    | '/admin/investors/'
    | '/admin/news/'
    | '/admin/performance/'
    | '/admin/products/'
    | '/admin/profile/'
    | '/admin/reports/'
    | '/admin/staff/'
    | '/admin/team/'
    | '/admin/withdrawals/'
    | '/app/activity/'
    | '/app/investments/'
    | '/app/notifications/'
    | '/app/performance/'
    | '/app/profile/'
    | '/app/reports/'
    | '/field/profile/'
    | '/app/investments/$investmentId/certificate'
    | '/app/reports/$transactionId/receipt'
    | '/field/reports/$reportId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/api/health'
    | '/app/wallet'
    | '/auth/forgot-password'
    | '/auth/kyc'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/farms/$farmSlug'
    | '/legal/investment-agreement'
    | '/legal/privacy'
    | '/legal/risk'
    | '/legal/terms'
    | '/news/$slug'
    | '/opportunities/$cycleId'
    | '/admin'
    | '/app'
    | '/farms'
    | '/field'
    | '/gallery'
    | '/news'
    | '/opportunities'
    | '/performance'
    | '/products'
    | '/admin/cycles/$cycleSlug'
    | '/admin/cycles/new'
    | '/admin/faq/$faqId'
    | '/admin/faq/new'
    | '/admin/farms/$farmSlug'
    | '/admin/farms/new'
    | '/admin/gallery/$itemSlug'
    | '/admin/gallery/new'
    | '/admin/inquiries/$inquiryId'
    | '/admin/investors/$investorId'
    | '/admin/news/$postSlug'
    | '/admin/news/new'
    | '/admin/products/$productSlug'
    | '/admin/products/new'
    | '/admin/team/$memberId'
    | '/admin/team/new'
    | '/api/webhooks/paystack'
    | '/app/invest/$cycleId'
    | '/field/reports/$reportId'
    | '/field/reports/new'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cycles'
    | '/admin/faq'
    | '/admin/farms'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/investors'
    | '/admin/news'
    | '/admin/performance'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/team'
    | '/admin/withdrawals'
    | '/app/activity'
    | '/app/investments'
    | '/app/notifications'
    | '/app/performance'
    | '/app/profile'
    | '/app/reports'
    | '/field/profile'
    | '/app/investments/$investmentId/certificate'
    | '/app/reports/$transactionId/receipt'
    | '/field/reports/$reportId/view'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/field'
    | '/about'
    | '/contact'
    | '/api/health'
    | '/app/wallet'
    | '/auth/forgot-password'
    | '/auth/kyc'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/farms/$farmSlug'
    | '/legal/investment-agreement'
    | '/legal/privacy'
    | '/legal/risk'
    | '/legal/terms'
    | '/news/$slug'
    | '/opportunities/$cycleId'
    | '/admin/'
    | '/app/'
    | '/farms/'
    | '/field/'
    | '/gallery/'
    | '/news/'
    | '/opportunities/'
    | '/performance/'
    | '/products/'
    | '/admin/cycles/$cycleSlug'
    | '/admin/cycles/new'
    | '/admin/faq/$faqId'
    | '/admin/faq/new'
    | '/admin/farms/$farmSlug'
    | '/admin/farms/new'
    | '/admin/gallery/$itemSlug'
    | '/admin/gallery/new'
    | '/admin/inquiries/$inquiryId'
    | '/admin/investors/$investorId'
    | '/admin/news/$postSlug'
    | '/admin/news/new'
    | '/admin/products/$productSlug'
    | '/admin/products/new'
    | '/admin/team/$memberId'
    | '/admin/team/new'
    | '/api/webhooks/paystack'
    | '/app/invest/$cycleId'
    | '/field/reports/$reportId'
    | '/field/reports/new'
    | '/admin/analytics/'
    | '/admin/audit/'
    | '/admin/cycles/'
    | '/admin/faq/'
    | '/admin/farms/'
    | '/admin/gallery/'
    | '/admin/inquiries/'
    | '/admin/investors/'
    | '/admin/news/'
    | '/admin/performance/'
    | '/admin/products/'
    | '/admin/profile/'
    | '/admin/reports/'
    | '/admin/staff/'
    | '/admin/team/'
    | '/admin/withdrawals/'
    | '/app/activity/'
    | '/app/investments/'
    | '/app/notifications/'
    | '/app/performance/'
    | '/app/profile/'
    | '/app/reports/'
    | '/field/profile/'
    | '/app/investments/$investmentId/certificate'
    | '/app/reports/$transactionId/receipt'
    | '/field/reports/$reportId/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  FieldRouteRoute: typeof FieldRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthKycRoute: typeof AuthKycRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  FarmsFarmSlugRoute: typeof FarmsFarmSlugRoute
  LegalInvestmentAgreementRoute: typeof LegalInvestmentAgreementRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRiskRoute: typeof LegalRiskRoute
  LegalTermsRoute: typeof LegalTermsRoute
  NewsSlugRoute: typeof NewsSlugRoute
  OpportunitiesCycleIdRoute: typeof OpportunitiesCycleIdRoute
  FarmsIndexRoute: typeof FarmsIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  PerformanceIndexRoute: typeof PerformanceIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/': {
      id: '/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof PerformanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/': {
      id: '/field/'
      path: '/'
      fullPath: '/field/'
      preLoaderRoute: typeof FieldIndexRouteImport
      parentRoute: typeof FieldRouteRoute
    }
    '/farms/': {
      id: '/farms/'
      path: '/farms'
      fullPath: '/farms/'
      preLoaderRoute: typeof FarmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/opportunities/$cycleId': {
      id: '/opportunities/$cycleId'
      path: '/opportunities/$cycleId'
      fullPath: '/opportunities/$cycleId'
      preLoaderRoute: typeof OpportunitiesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risk': {
      id: '/legal/risk'
      path: '/legal/risk'
      fullPath: '/legal/risk'
      preLoaderRoute: typeof LegalRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/investment-agreement': {
      id: '/legal/investment-agreement'
      path: '/legal/investment-agreement'
      fullPath: '/legal/investment-agreement'
      preLoaderRoute: typeof LegalInvestmentAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/$farmSlug': {
      id: '/farms/$farmSlug'
      path: '/farms/$farmSlug'
      fullPath: '/farms/$farmSlug'
      preLoaderRoute: typeof FarmsFarmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/kyc': {
      id: '/auth/kyc'
      path: '/auth/kyc'
      fullPath: '/auth/kyc'
      preLoaderRoute: typeof AuthKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/profile/': {
      id: '/field/profile/'
      path: '/profile'
      fullPath: '/field/profile/'
      preLoaderRoute: typeof FieldProfileIndexRouteImport
      parentRoute: typeof FieldRouteRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/performance/': {
      id: '/app/performance/'
      path: '/performance'
      fullPath: '/app/performance/'
      preLoaderRoute: typeof AppPerformanceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/': {
      id: '/app/investments/'
      path: '/investments'
      fullPath: '/app/investments/'
      preLoaderRoute: typeof AppInvestmentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity/': {
      id: '/app/activity/'
      path: '/activity'
      fullPath: '/app/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/withdrawals/': {
      id: '/admin/withdrawals/'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals/'
      preLoaderRoute: typeof AdminWithdrawalsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/team'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/profile'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/performance/': {
      id: '/admin/performance/'
      path: '/performance'
      fullPath: '/admin/performance/'
      preLoaderRoute: typeof AdminPerformanceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/investors/': {
      id: '/admin/investors/'
      path: '/investors'
      fullPath: '/admin/investors/'
      preLoaderRoute: typeof AdminInvestorsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/gallery'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/farms/': {
      id: '/admin/farms/'
      path: '/farms'
      fullPath: '/admin/farms/'
      preLoaderRoute: typeof AdminFarmsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faq/': {
      id: '/admin/faq/'
      path: '/faq'
      fullPath: '/admin/faq/'
      preLoaderRoute: typeof AdminFaqIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cycles/': {
      id: '/admin/cycles/'
      path: '/cycles'
      fullPath: '/admin/cycles/'
      preLoaderRoute: typeof AdminCyclesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/field/reports/new': {
      id: '/field/reports/new'
      path: '/reports/new'
      fullPath: '/field/reports/new'
      preLoaderRoute: typeof FieldReportsNewRouteImport
      parentRoute: typeof FieldRouteRoute
    }
    '/field/reports/$reportId': {
      id: '/field/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/field/reports/$reportId'
      preLoaderRoute: typeof FieldReportsReportIdRouteImport
      parentRoute: typeof FieldRouteRoute
    }
    '/app/invest/$cycleId': {
      id: '/app/invest/$cycleId'
      path: '/invest/$cycleId'
      fullPath: '/app/invest/$cycleId'
      preLoaderRoute: typeof AppInvestCycleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/new': {
      id: '/admin/team/new'
      path: '/team/new'
      fullPath: '/admin/team/new'
      preLoaderRoute: typeof AdminTeamNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/$memberId': {
      id: '/admin/team/$memberId'
      path: '/team/$memberId'
      fullPath: '/admin/team/$memberId'
      preLoaderRoute: typeof AdminTeamMemberIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$productSlug': {
      id: '/admin/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/admin/products/$productSlug'
      preLoaderRoute: typeof AdminProductsProductSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/$postSlug': {
      id: '/admin/news/$postSlug'
      path: '/news/$postSlug'
      fullPath: '/admin/news/$postSlug'
      preLoaderRoute: typeof AdminNewsPostSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/investors/$investorId': {
      id: '/admin/investors/$investorId'
      path: '/investors/$investorId'
      fullPath: '/admin/investors/$investorId'
      preLoaderRoute: typeof AdminInvestorsInvestorIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries/$inquiryId': {
      id: '/admin/inquiries/$inquiryId'
      path: '/inquiries/$inquiryId'
      fullPath: '/admin/inquiries/$inquiryId'
      preLoaderRoute: typeof AdminInquiriesInquiryIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery/new': {
      id: '/admin/gallery/new'
      path: '/gallery/new'
      fullPath: '/admin/gallery/new'
      preLoaderRoute: typeof AdminGalleryNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery/$itemSlug': {
      id: '/admin/gallery/$itemSlug'
      path: '/gallery/$itemSlug'
      fullPath: '/admin/gallery/$itemSlug'
      preLoaderRoute: typeof AdminGalleryItemSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/farms/new': {
      id: '/admin/farms/new'
      path: '/farms/new'
      fullPath: '/admin/farms/new'
      preLoaderRoute: typeof AdminFarmsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/farms/$farmSlug': {
      id: '/admin/farms/$farmSlug'
      path: '/farms/$farmSlug'
      fullPath: '/admin/farms/$farmSlug'
      preLoaderRoute: typeof AdminFarmsFarmSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faq/new': {
      id: '/admin/faq/new'
      path: '/faq/new'
      fullPath: '/admin/faq/new'
      preLoaderRoute: typeof AdminFaqNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faq/$faqId': {
      id: '/admin/faq/$faqId'
      path: '/faq/$faqId'
      fullPath: '/admin/faq/$faqId'
      preLoaderRoute: typeof AdminFaqFaqIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cycles/new': {
      id: '/admin/cycles/new'
      path: '/cycles/new'
      fullPath: '/admin/cycles/new'
      preLoaderRoute: typeof AdminCyclesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cycles/$cycleSlug': {
      id: '/admin/cycles/$cycleSlug'
      path: '/cycles/$cycleSlug'
      fullPath: '/admin/cycles/$cycleSlug'
      preLoaderRoute: typeof AdminCyclesCycleSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/field/reports/$reportId/view': {
      id: '/field/reports/$reportId/view'
      path: '/view'
      fullPath: '/field/reports/$reportId/view'
      preLoaderRoute: typeof FieldReportsReportIdViewRouteImport
      parentRoute: typeof FieldReportsReportIdRoute
    }
    '/app/reports/$transactionId/receipt': {
      id: '/app/reports/$transactionId/receipt'
      path: '/reports/$transactionId/receipt'
      fullPath: '/app/reports/$transactionId/receipt'
      preLoaderRoute: typeof AppReportsTransactionIdReceiptRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/$investmentId/certificate': {
      id: '/app/investments/$investmentId/certificate'
      path: '/investments/$investmentId/certificate'
      fullPath: '/app/investments/$investmentId/certificate'
      preLoaderRoute: typeof AppInvestmentsInvestmentIdCertificateRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCyclesCycleSlugRoute: typeof AdminCyclesCycleSlugRoute
  AdminCyclesNewRoute: typeof AdminCyclesNewRoute
  AdminFaqFaqIdRoute: typeof AdminFaqFaqIdRoute
  AdminFaqNewRoute: typeof AdminFaqNewRoute
  AdminFarmsFarmSlugRoute: typeof AdminFarmsFarmSlugRoute
  AdminFarmsNewRoute: typeof AdminFarmsNewRoute
  AdminGalleryItemSlugRoute: typeof AdminGalleryItemSlugRoute
  AdminGalleryNewRoute: typeof AdminGalleryNewRoute
  AdminInquiriesInquiryIdRoute: typeof AdminInquiriesInquiryIdRoute
  AdminInvestorsInvestorIdRoute: typeof AdminInvestorsInvestorIdRoute
  AdminNewsPostSlugRoute: typeof AdminNewsPostSlugRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminProductsProductSlugRoute: typeof AdminProductsProductSlugRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminTeamMemberIdRoute: typeof AdminTeamMemberIdRoute
  AdminTeamNewRoute: typeof AdminTeamNewRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminCyclesIndexRoute: typeof AdminCyclesIndexRoute
  AdminFaqIndexRoute: typeof AdminFaqIndexRoute
  AdminFarmsIndexRoute: typeof AdminFarmsIndexRoute
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
  AdminInvestorsIndexRoute: typeof AdminInvestorsIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminPerformanceIndexRoute: typeof AdminPerformanceIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
  AdminWithdrawalsIndexRoute: typeof AdminWithdrawalsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCyclesCycleSlugRoute: AdminCyclesCycleSlugRoute,
  AdminCyclesNewRoute: AdminCyclesNewRoute,
  AdminFaqFaqIdRoute: AdminFaqFaqIdRoute,
  AdminFaqNewRoute: AdminFaqNewRoute,
  AdminFarmsFarmSlugRoute: AdminFarmsFarmSlugRoute,
  AdminFarmsNewRoute: AdminFarmsNewRoute,
  AdminGalleryItemSlugRoute: AdminGalleryItemSlugRoute,
  AdminGalleryNewRoute: AdminGalleryNewRoute,
  AdminInquiriesInquiryIdRoute: AdminInquiriesInquiryIdRoute,
  AdminInvestorsInvestorIdRoute: AdminInvestorsInvestorIdRoute,
  AdminNewsPostSlugRoute: AdminNewsPostSlugRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminProductsProductSlugRoute: AdminProductsProductSlugRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminTeamMemberIdRoute: AdminTeamMemberIdRoute,
  AdminTeamNewRoute: AdminTeamNewRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminCyclesIndexRoute: AdminCyclesIndexRoute,
  AdminFaqIndexRoute: AdminFaqIndexRoute,
  AdminFarmsIndexRoute: AdminFarmsIndexRoute,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
  AdminInvestorsIndexRoute: AdminInvestorsIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminPerformanceIndexRoute: AdminPerformanceIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
  AdminWithdrawalsIndexRoute: AdminWithdrawalsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInvestCycleIdRoute: typeof AppInvestCycleIdRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
  AppInvestmentsIndexRoute: typeof AppInvestmentsIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppPerformanceIndexRoute: typeof AppPerformanceIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppInvestmentsInvestmentIdCertificateRoute: typeof AppInvestmentsInvestmentIdCertificateRoute
  AppReportsTransactionIdReceiptRoute: typeof AppReportsTransactionIdReceiptRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppInvestCycleIdRoute: AppInvestCycleIdRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
  AppInvestmentsIndexRoute: AppInvestmentsIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppPerformanceIndexRoute: AppPerformanceIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppInvestmentsInvestmentIdCertificateRoute:
    AppInvestmentsInvestmentIdCertificateRoute,
  AppReportsTransactionIdReceiptRoute: AppReportsTransactionIdReceiptRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface FieldReportsReportIdRouteChildren {
  FieldReportsReportIdViewRoute: typeof FieldReportsReportIdViewRoute
}

const FieldReportsReportIdRouteChildren: FieldReportsReportIdRouteChildren = {
  FieldReportsReportIdViewRoute: FieldReportsReportIdViewRoute,
}

const FieldReportsReportIdRouteWithChildren =
  FieldReportsReportIdRoute._addFileChildren(FieldReportsReportIdRouteChildren)

interface FieldRouteRouteChildren {
  FieldIndexRoute: typeof FieldIndexRoute
  FieldReportsReportIdRoute: typeof FieldReportsReportIdRouteWithChildren
  FieldReportsNewRoute: typeof FieldReportsNewRoute
  FieldProfileIndexRoute: typeof FieldProfileIndexRoute
}

const FieldRouteRouteChildren: FieldRouteRouteChildren = {
  FieldIndexRoute: FieldIndexRoute,
  FieldReportsReportIdRoute: FieldReportsReportIdRouteWithChildren,
  FieldReportsNewRoute: FieldReportsNewRoute,
  FieldProfileIndexRoute: FieldProfileIndexRoute,
}

const FieldRouteRouteWithChildren = FieldRouteRoute._addFileChildren(
  FieldRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  FieldRouteRoute: FieldRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthKycRoute: AuthKycRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  FarmsFarmSlugRoute: FarmsFarmSlugRoute,
  LegalInvestmentAgreementRoute: LegalInvestmentAgreementRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRiskRoute: LegalRiskRoute,
  LegalTermsRoute: LegalTermsRoute,
  NewsSlugRoute: NewsSlugRoute,
  OpportunitiesCycleIdRoute: OpportunitiesCycleIdRoute,
  FarmsIndexRoute: FarmsIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  PerformanceIndexRoute: PerformanceIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
